  spring:
    h2.console:
      enabled: true
      path: '/console'
    datasource:
      url: 'jdbc:h2:file:C:/Users/Justyna/Desktop/todo-app/todo-app/todo-db'
    flyway.baseline-on-migrate : true
    jpa:
      hibernate:
        ddl-auto: validate